name: CI

env:
  CI: true
  TZ: Europe/Paris
  NODE_VERSION: 13.x

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - run: echo wip
